export default {
  CARD: "card",
  HEADER: "header",
  SUBHEADER: "subheader",
  PARAGRAPH: "paragraph",
  IMPORTANT_TEXT: "important_text",
  ORDERED_LIST: "ol",
  UNORDERED_LIST: "ul",
  DIVIDER: "divider",
  DIVIDER_NOLINE: "divider_noline",
  IMAGE: "image",
  BOX: "box",
  IMAGE: "image",
  TABLE: "table",
  ALPHABETICAL_HEADER: "alphabetical",
  FORMULA: "formula",
  LINK: "link",
};
