-- Run on master
-- CREATE LOGIN ADFUser WITH PASSWORD='abcdEFGH123'
-- GO

-- Run on events database
CREATE USER ADFUser;
GO
GRANT INSERT ON DevEvents TO ADFUser;
GO

CREATE TABLE DevEvents (
  PartitionKey NVARCHAR(64) NOT NULL ,
  RowKey NVARCHAR(64) NOT NULL ,
  ServerTime DATETIMEOFFSET NOT NULL,
  EventTime DATETIMEOFFSET NOT NULL ,
  AppId NVARCHAR(64) NOT NULL ,
  SessId NVARCHAR(64) NOT NULL,
  UserId NVARCHAR(64),
  EventType NVARCHAR(256) NOT NULL,
  EventData NVARCHAR(1024) NOT NULL,
  LocType NVARCHAR(32),
  Lat DOUBLE PRECISION,
  Lon DOUBLE PRECISION,
  Slice BINARY(32)
)

GO

CREATE TABLE Events (
  PartitionKey NVARCHAR(64) NOT NULL ,
  RowKey NVARCHAR(64) NOT NULL ,
  ServerTime DATETIMEOFFSET NOT NULL,
  EventTime DATETIMEOFFSET NOT NULL ,
  AppId NVARCHAR(64) NOT NULL ,
  SessId NVARCHAR(64) NOT NULL,
  UserId NVARCHAR(64),
  EventType NVARCHAR(256) NOT NULL,
  EventData NVARCHAR(1024) NOT NULL,
  LocType NVARCHAR(32),
  Lat DOUBLE PRECISION,
  Lon DOUBLE PRECISION,
  Slice BINARY(32)
)
GO
